class FilterError(Exception):
    pass


class SassFilterError(FilterError):
    """
    SassError parses syntax errors generated by Sass and formats them
    for Django.
    """
    def __init__(self, stacktrace):
        stacktrace = stacktrace.strip().split(b'\n')[:-1]
        message = b'\n'.join(stacktrace)
        super(SassFilterError, self).__init__(message)


class CoffeeScriptFilterError(FilterError):
    """
    CoffeeScriptError parses syntax errors generated by CoffeeScript and
    formats them for Django.
    """
    pass
